name: catkin_build

on: [push]

env:
  ROS_DISTRO: noetic

defaults:
  run:
    shell: bash
jobs:
  catkin_build:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic
    steps:
      - run: apt-get update && apt-get install -y git
      - run: if [[ "$ROS_DISTRO" = "noetic" ]] ;  then apt-get install -y python3-pip ros-noetic-catkin python3-catkin-tools ; fi
      - run: if [[ "$ROS_DISTRO" = "melodic" ]] ; then apt-get install -y python-catkin-tools python-pip python3-pip python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential python-catkin-tools ; fi

      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/cyphal_communicator

      - name: Install requirements
        run: ./catkin_ws/src/cyphal_communicator/install_requirements.sh

      - name: Compile DSDL
        run: ./catkin_ws/src/cyphal_communicator/compile_dsdl.sh

      - name: Catkin build
        run: source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build
