name: build

on: [push]

env:
  ROS_DISTRO: noetic

defaults:
  run:
    shell: bash
jobs:
  ros_interface:
    runs-on: ubuntu-22.04
    container:
      image: ros:noetic
    steps:
      - name: Handle issue with actions/checkout when Git version is less than 2.18 
        run: apt-get update && apt-get install -y git

      - uses: actions/checkout@v4
        with:
          path: catkin_ws/src/cyphal_communicator
          submodules: recursive

      - name: Install requirements
        run: ./catkin_ws/src/cyphal_communicator/scripts/install.sh --full

      - name: Catkin build
        run: source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build

  ap_json_interface:
    runs-on: ubuntu-22.04
    container:
      image: ros:noetic
    steps:
      - name: Handle issue with actions/checkout when Git version is less than 2.18 
        run: apt-get update && apt-get install -y git

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install requirements
        run: ./scripts/install.sh --full

      - name: Catkin build
        run: mkdir build && cd build && cmake .. -DARDUPILOT_JSON_SIM_INTERFACE=1 . && make
