name: build

on: [push]

env:
  ROS_DISTRO: noetic

defaults:
  run:
    shell: bash
jobs:
  ros_interface:
    runs-on: ubuntu-22.04
    container:
      image: ros:noetic
    steps:
      - run: apt-get update && apt-get install -y git
      - run: if [[ "$ROS_DISTRO" = "noetic" ]] ;  then apt-get install -y python3-pip ros-noetic-catkin python3-catkin-tools ; fi

      - uses: actions/checkout@v2
        with:
          path: catkin_ws/src/cyphal_communicator
          submodules: recursive

      - name: Install requirements
        run: ./catkin_ws/src/cyphal_communicator/install_requirements.sh

      - name: Catkin build
        run: source /opt/ros/noetic/setup.bash && cd catkin_ws && catkin build

  ap_json_interface:
    runs-on: ubuntu-22.04
    container:
      image: ros:noetic
    steps:
      - run: apt-get update && apt-get install -y git python3-pip

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install requirements
        run: ./install_requirements.sh

      - name: Catkin build
        run: |
          mkdir build
          cd build
          cmake .. -DARDUPILOT_JSON_SIM_INTERFACE=1 .
          make
